### ISSUE TITLE
_initializeProto is a deferred-generator but is not yielded

### ISSUE THREAD

**Issue by carl-amplidata** [twisted/txmongo#129]
I believe that the _initializeProto is used incorrectly
It returns a deferred-generator, but we do not yield it (moreover I think yield would not work inside buildProtocol).

https://github.com/twisted/txmongo/blob/master/txmongo/connection.py#L51

**Comment by fiorix** [comment]
Looks like this commit is the culprit: https://github.com/twisted/txmongo/commit/aa72878a0239d8979ea987446098a090719cfd71?diff=split

**Comment by IlyaSkriblovsky** [comment]
You are right, it is not possible to wait for deferred in `buildProtocol`. But it's ok: deferred execution of `_initializeProto` ends with one of calls:
1. `setInstance(proto)`. This notifies listeners, registered via `notifyReady`, and this connection comes to play within the Pool.
2. `proto.fail(e)`, which in part calls `proto.transport.loseConnection` which leads to `Connection.clientConnectionLost` and causes `Connection.retryNextHost` call.

`@inlineCallbacks` is used on `_initializeProto` just to support `yields` inside itself, not to return some meaningful deferred.

**Comment by carl-amplidata** [comment]
Hi

Are you sure that is how it works?
I believe that if you call _initializeProto (instead of yielding), which returns a python generator, you will only execute the code in _initializeProto until the first yield (i.e.  yield proto.connectionReady())

I think the remaining lines of _initializeProto are never executed.

But I might be wrong.


From: Ilya Skriblovsky
Reply-To: twisted/txmongo
Date: Thursday 17 September 2015 08:58
To: twisted/txmongo
Cc: Carl D'Halluin
Subject: Re: [txmongo] _initializeProto is a deferred-generator but is not yielded (#129)


You are right, it is not possible to wait for deferred in buildProtocol. But it's ok: deferred execution of _initializeProto ends with one of calls:
1. setInstance(proto). This notifies listeners, registered via notifyReady, and this connection comes to play within the Pool.
2. proto.fail(e), which in part calls proto.transport.loseConnection which leads to Connection.clientConnectionLost and causes Connection.retryNextHost call.

@inlineCallbacks is used on _initializeProto just to support yields inside itself, not to return some meaningful deferred.

—
Reply to this email directly or view it on GitHub<https://github.com/twisted/txmongo/issues/129#issuecomment-140987140>.
HGST E-mail Confidentiality Notice & Disclaimer:
This e-mail and any files transmitted with it may contain confidential or legally privileged information of HGST and are intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited.  If you have received this e-mail in error, please notify the sender immediately and delete the e-mail in its entirety from your system.

**Comment by IlyaSkriblovsky** [comment]
No, it is `inlineCallbacks` that unwinds generator until its end, not `yield`ed call.
`inlineCallbacks` makes function return `Deferred` which fires when function ends. There are no means how `yield` can assist function execution because it only receives that Deferred. It only waits until it is ready.

Consider following example:
```
@defer.inlineCallbacks
def f():
    print 'before'

    d = defer.Deferred()
    reactor.callLater(3, d.callback, None)
    yield d

    print 'after'
    reactor.stop()                                                              

f()
reactor.run()
```

It runs `f()` to end although its execution is not waited.

**Comment by carl-amplidata** [comment]
OK thanks so calling an inlinecallback without yield, is sort of a fire-and-forget

Thanks for educating me !
