### ISSUE TITLE
collection's count() return floating value

### ISSUE THREAD

**Issue by ygl-rg** [twisted/txmongo#133]
Hi

   I noticed the count() function of collection returned floating value but pymongo return integer value which is correct.

    Is it a bug?

Regards

gelin yan

**Comment by IlyaSkriblovsky** [comment]
Yes, I think this is a bug. We need to fix it.

**Comment by psi29a** [comment]
Thanks, I'll fix it in a minute. :)

pymong/collection.py
```
    def _count(self, cmd):
        """Internal count helper."""
        with self._socket_for_reads() as (sock_info, slave_ok):
            res = self._command(sock_info, cmd, slave_ok,
                                allowable_errors=["ns missing"])
        if res.get("errmsg", "") == "ns missing":
            return 0
        return int(res["n"])
```

**Comment by psi29a** [comment]
Should be fixed here:
https://github.com/psi29a/txmongo/commit/b8d7ef4e2a9bbee4a3d3eb0b394d2374ae075295

Can you verify that this works for you?

**Comment by ygl-rg** [comment]
thx. it is fixed.
