### ISSUE TITLE
GEO2D and ensure_index Support

### ISSUE THREAD

**Issue by taylanpince** [twisted/txmongo#14]
I was wondering about GEO2D indexes and ensure_index support. As far as I can see, this is not supported in the current txmongo, but I am not sure how hard it would be to support. When I try to create_index a GEO2D index, I get the following exception:

sort_fields must be an instance of filter.sort

Trying to use ensure_index failed as well - this would be a nice to have.

Let me know if I can help in any way. I have a good knowledge of MongoDB but I am not that well-versed in Twisted so I didn't want to just fork start hacking, but I'll be happy to look at it if you point me in the right direction.

**Comment by psi29a** [comment]
@kientzlecatch Would be so kind as to make a pull request? :)

**Comment by psi29a** [comment]
@rnz0 Do you still have that pull request? 

@gleicon I can also review and test this if the PR is there.

**Comment by gleicon** [comment]
thanks @psi29a I don't see the PR anymore. In any case if you want to work on it let me know how I can help.

**Comment by psi29a** [comment]
This looks to be partially enabled, we have GEO2D support but the ensure_index is just a wrapper around create_index.

As of pymongo 3.0, ensure_index is deprecated. So as far as I'm concerned, this can be closed.

Any objections or comments?

**Comment by gleicon** [comment]
Ok for me. I've proceeded with some tests at the time this was opened but didn't had the full grasp of GEO + mongo to submit something meaningful. Ping me if you need any help. Thanks.

**Comment by fiorix** [comment]
+1
