### ISSUE TITLE
nearest read preference

### ISSUE THREAD

**Issue by linearb** [twisted/txmongo#152]
Does txmongo support nearest read preference? 
I don't see it in the code.
Thanks.

**Comment by IlyaSkriblovsky** [comment]
No, TxMongo doesn't support `read_preference` yet

**Comment by linearb** [comment]
Ok - thanks. It'd be good to get support for read preference in sometime.

I guess there is a bit so far: in connection.py when read preference in
the options is primary or primary preferred it immediately configures and gets all the 
members of the replset--- so it fails over when the primary changes or fails. 

Surprisingly, I noticed that when read preference is secondary it doesn't configure and 
get all the members of the replset. Is that behavior expected? I would have thought that 
the task looping call would have run.

**Comment by IlyaSkriblovsky** [comment]
Wow, this is certainly a bug. Could you please create a distinct issue for this? Thanks for noticing!

**Comment by linearb** [comment]
Closing this issue. Thanks for answer. I'll add an issue for that possible bug.
Also, I'd add a feature request issue for read preferences to be supported-- it'd be great
to get that in.
