### ISSUE TITLE
Not compatible for python 2.6 

### ISSUE THREAD

**Issue by dynamikdev** [twisted/txmongo#154]
There is a dict comprehension mechanism on connection.py, line 19
`_PRIMARY_READ_PREFERENCES = {ReadPreference.PRIMARY.mode, ReadPreference.PRIMARY_PREFERRED.mode}`
So it is not compatible with 2.6 version of python

**Comment by IlyaSkriblovsky** [comment]
Twisted had dropped Python 2.6 support in 16.0.0, so we did the same. TxMongo only supports 2.7 and 3.3+.

(Btw, this is set literal, not dict comprehension)

**Comment by dynamikdev** [comment]
ok you right twice time :) , i check how to update my server version (argg ) 
btw , you should update compatibility annoucment on pypi : https://pypi.python.org/pypi/txmongo/15.3.0

> Compatibility

>Python 2.6, 2.7, 3.0, 3.3, 3.4 and PyPy.

**Comment by dynamikdev** [comment]
you right sorry i have a look at youre 15.* package and installed the 16.0.1
Excuse me again

**Comment by IlyaSkriblovsky** [comment]
Compatibility is already updated in latest version: https://pypi.python.org/pypi/txmongo/16.0.1

Actually, it shouldn't be hard to support 2.6 in TxMongo. But since Twisted dropped support on their side, it doesn't worth for us to continue support legacy python version.

**Comment by boogheta** [comment]
Although it would be nice if trying to install txmongo on systems using python2.6 would limit itself to compatible versions (meaning Twisted14 max as well)

**Comment by IlyaSkriblovsky** [comment]
It is not TxMongo who installs twisted, but `pip`. Even if TxMongo will detect py2.6 and modify its `install_requires` in `setup.py` to require `twisted<15.0` (sounds like a dirty hack), you are still required to install proper version of TxMongo itself.
