### ISSUE TITLE
collection.save method could't update a document that already exists ?

### ISSUE THREAD

**Issue by Demon-Hunter** [twisted/txmongo#155]
When I use collection's save method, I would like to save a document if the `doc ` param take the `_id` field, but it could't work.
I think that the `upsert ` param (https://github.com/twisted/txmongo/blob/master/txmongo/collection.py#L612) must be `False` if there has the param `_id` in method save.

**Comment by IlyaSkriblovsky** [comment]
Sorry, I didn't get your point. If you do `save({"_id": ObjectId(...), ...})` it should:

1. Replace existing document if there is document with same `_id` in collection
2. Add new document to collection, if collection doesn't have one with same `_id`

`update` with `upsert=True` does exactly this. With `upsert=False` it could do only the # 1.

Could you please give an example of input, expected output and actual output if I get you wrong?

**Comment by Demon-Hunter** [comment]
I'm so sorry that I make a mistake in mongodb's `update` method, there's no any doubts at this point.
Thank you very much! txmongo is very nice! :)

**Comment by IlyaSkriblovsky** [comment]
Thanks :-)

**Comment by psi29a** [comment]
Thank you! :D
