### ISSUE TITLE
Considering putting documentation on readthedocs

### ISSUE THREAD

**Issue by touilleMan** [twisted/txmongo#156]
Hi,

It seems the documentation of the project is not available on line.
Having to get the sources and do a `make docs` is pretty cumbersome so I think it would be better to put it on [readthedocs](https://readthedocs.org/). If you don't have time I can help doing this ;-)

PS: thanks for the nice lib, I'm using it to write [a new ODM](https://github.com/Scille/umongo)

**Comment by IlyaSkriblovsky** [comment]
We already have something: https://txmongo.readthedocs.org/en/latest/txmongo.html
But it seems to be outdated a bit (15.3.0) and also txmongo's docs look very laconic: https://txmongo.readthedocs.org/en/latest/txmongo.html#module-txmongo.collection :-/

**Comment by psi29a** [comment]
Just re-installed the webhook, apparently something hiccuped awhile back. Now tag pushes will trigger new builds.

**Comment by psi29a** [comment]
If you would like to spruce up the the documentation, please do. :)

**Comment by touilleMan** [comment]
So the doc was already in place, my mistake ;-)

I think we should add a link to it in the README to make it more visible then

**Comment by IlyaSkriblovsky** [comment]
I've started to fill the API docs in [better-docs branch in my fork](https://github.com/IlyaSkriblovsky/txmongo/tree/better-docs).
I would appreciate for proofreading and checking for grammar and factual errors.

**Comment by touilleMan** [comment]
I'll have a look :+1:
