### ISSUE TITLE
GridFS default chunkSize is no more 256k

### ISSUE THREAD

**Issue by touilleMan** [twisted/txmongo#158]
[The param `chunkSize`](https://github.com/twisted/txmongo/blob/master/txmongo/_gridfs/grid_file.py#L29) is by default 256k in txmongo. However it is [no longer the default](https://docs.mongodb.org/manual/core/gridfs/) in MongoDB since 2.4.10:

> Changed in version 2.4.10: The default chunk size changed from 256 kB to 255 kB.

Reason invoked for this is "[to avoid overhead with usePowerOf2Sizes ](https://docs.mongodb.org/manual/release-notes/2.4-changelog/#id8)".

So I guess keep 256k as default in txmongo doesn't break anything, but it should be corrected anyway to get rid of this overhead and to stay consistent with default behavior.

I can do the PR if needed

**Comment by IlyaSkriblovsky** [comment]
Please, make a PR

**Comment by touilleMan** [comment]
see #159 ;-)

**Comment by psi29a** [comment]
Thanks!
