### ISSUE TITLE
GridFS.get messing when file is not found

### ISSUE THREAD

**Issue by touilleMan** [twisted/txmongo#160]
`GridFS.get` uses `find_one` to retrieve the requested file from the collection.
However nothing is done if the returned value is None, which leads to...

```python
>>> gridout = yield GridFS.get('dummy')
>>> gridout
None
>>> not gridout
False
>>> bool(gridout)
True
>>> type(gridout)
<class 'txmongo._gridfs.grid_file.GridOut'>
```
:trollface:

Of course the returned GridOut object is not usable
```python
>>> gridout.name
*** TypeError: argument of type 'NoneType' is not iterable
```

I think `GridFS.get` should raises a `NoFile` in such case [to be conform with pymongo](https://github.com/mongodb/mongo-python-driver/blob/master/gridfs/__init__.py#L139)

**Comment by psi29a** [comment]
I agree! :)  

If you would like to do this, please do, add a test-case for it and fire off a pull request. Otherwise we'll get around to it eventually.
