### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by oddjobz** [twisted/txmongo#201]
Hi Guys,

Any chance of a new release .. it'd be really cool to be able to use "get_version" using a pip install rather than having to use a custom repo ... :)

**Comment by IlyaSkriblovsky** [comment]
Sure!

#202

**Comment by psi29a** [comment]
done and done! :)

**Comment by oddjobz** [comment]
:) 

tvm. 

Gareth Bult 
iFlex Real Time Systems 
Tel: 07853 305393, Skype: gareth_bult 
iFlexRTS is a limited company registered in England and Wales (10108171) 
Statements made are at all times subject to iFlexRTS's Terms and Conditions of Business, which are available upon request.
