### ISSUE TITLE
Pymongo 3.5.0 doesn't provide _WriteOp in pymongo.operations

### ISSUE THREAD

**Issue by bhyde** [twisted/txmongo#210]
This line:

https://github.com/twisted/txmongo/blob/c960defdb8190d2e66aaea88c13e163498b1784c/txmongo/collection.py#L17

 is failing since recent release of pymongo 3.5.0.

Pinning to 3.4.0 is a work around.

**Comment by bhyde** [comment]
See also: https://github.com/mongodb/mongo-python-driver/commit/9468c119a31b5809dc5883605b5be91eb4bc57ac#diff-e03bf8345fe8fe509a1d13a5e75edb26

**Comment by psi29a** [comment]
@bhyde Thank you for reporting this!

Looks like we only import _WriteOp to validate that the bulk_insert request is of instance _WriteOp. If I understand correctly, pymongo instead just does a try/except around request._add_to_bulk(blk) in which case we can do the same.

@IlyaSkriblovsky Do you agree?

**Comment by IlyaSkriblovsky** [comment]
Sure, fixed in #211
Thanks, Ben!

**Comment by psi29a** [comment]
@IlyaSkriblovsky I was looking for consensus that my assumption was correct, not that you do the work! ;)

**Comment by IlyaSkriblovsky** [comment]
Sorry, it's sometimes hard to resist when fingers reach the keyboard :)

**Comment by psi29a** [comment]
Hah! No worries!

**Comment by bhyde** [comment]
Oh, nice turn around.  Awesome.  I'll keep an eye out for a release.   Thanks!

**Comment by psi29a** [comment]
Merged... going to close this. If there is a still an issue, please re-open.

Cheers!
