### ISSUE TITLE
Method coll.insert_one Incompatible with PyMongo 3.6

### ISSUE THREAD

**Issue by grammy-jiang** [twisted/txmongo#220]
In txmongo 17.1.0, the method `coll.insert_one` is incompatible with the latest version, pymongo 3.6.

The return of this method is:

```
Unhandled error in Deferred:
```

and the reactor does not stop. 

I have tested: with pymongo 3.5, everything is fine.

**Comment by IlyaSkriblovsky** [comment]
Yep, it is already fixed in #219, but not merged yet

**Comment by grammy-jiang** [comment]
@IlyaSkriblovsky oh, thanks for your notice!

**Comment by IlyaSkriblovsky** [comment]
TxMongo 18.0.0 released today is fixing this issue
