### ISSUE TITLE
How I can find in a colletion nested

### ISSUE THREAD

**Issue by rzavarce** [twisted/txmongo#223]
Hi, my collection has the current json estructure:

Example:
{
"father_name":"peter", 
"age":"32", 
"sons":[ {"name":"junior"},{"name":"brian"}]
}

I need find the father with sons name is junior, for exmple.

I tried  db.persons.find({'sons.name': 'junior'}), and other types of querys estructure but allways the result arrive empty. In the mongo's console all OK, but in TXMONGO I can't do it.

Can you help me pleases.

**Comment by IlyaSkriblovsky** [comment]
Hi,

This is very strange, `{'sons.name': 'junior'}` query shoud work with txmongo. Actually, txmongo doesn't do anything with queries and simply passes it to MongoDB. Could you please show some minimal working example of the issue?

**Comment by rzavarce** [comment]
Hi, Thank you.

You are right, I have reviewed my code and had one error with the connection to mongo, that's why the find uqery did not work.

Thank you very much for your help.

**Comment by psi29a** [comment]
Glad you found the problem. :)
