### ISSUE TITLE
How to set timeout uniformly？

### ISSUE THREAD

**Issue by zkqiang** [twisted/txmongo#237]
Can I set the default timeout for mongo methods(find insert update) when use ConnectionPool？

**Comment by IlyaSkriblovsky** [comment]
No, you can't currently specify default timeouts for operation, only `ping_interval` and `ping_timeout` for the watchdog that checks connection liveness

**Comment by zkqiang** [comment]
Thank you for answering, hope to have this feature, because currently if I don't set timeout, it will wait forever when loss connection.

**Comment by IlyaSkriblovsky** [comment]
Normally txmongo's ConnectionPool starts watchdog pinger which pings MongoDB every 10 seconds and waits for response for another 10 seconds. If it doesn't receive response, it breaks connection, failing all pending queries and tries to reconnect.
So, in case of failed connection queries shouldn't be hanging forever.

**Comment by zkqiang** [comment]
I thought so before, until one time, my mongo server was down, the first find_one has been pending forever.  This makes me have to set timeout in operations.
I use txmongo in scrapy, and default params, so the watchdog should be open.

**Comment by IlyaSkriblovsky** [comment]
That's strange... Are you sure you are using recent version of txmongo?

**Comment by zkqiang** [comment]
Yes, I am sure its 18.1.0, because I set txmongo >= 18.1.0 in requirements.txt

**Comment by IlyaSkriblovsky** [comment]
Is there some reliable way to reproduce the issue? We are certainly interested to avoid infinite hangs in case of server availability problems.
