### ISSUE TITLE
get filemd5 error when gridfs.close (OperationFailure)

### ISSUE THREAD

**Issue by sagnol** [twisted/txmongo#239]
### Environments
python 3.6 (pipenv)
mongodb 3.6.6 (docker)

### Error stack
```
raise OperationFailure(msg % errmsg, code, response)
	pymongo.errors.OperationFailure: TxMongo:  
command SON([('filemd5', ObjectId('5b88c0e325ac92202a15bb68')), ('root', 'attachments')])  
on namespace mycollection.$cmd failed with 'error processing query:  
ns=mycollection.attachments.chunksTree: 
      $and
	    files_id $eq ObjectId('5b88c0e325ac92202a15bb68')
	    n $gte 0
	Sort: { files_id: 1, n: 1 }
	Proj: {}
	 No query solutions'
```

```!python
    .addCallback(lambda _: self._coll.filemd5(self._id))\ # Error Occured
```
https://github.com/twisted/txmongo/blob/master/txmongo/_gridfs/grid_file.py#L177

  
but it has fixed when i get md5 using hashlib.md5 likes pymongo
https://github.com/mongodb/mongo-python-driver/blob/98e77ba1d2f59061bcf4cc529369001823af1c13/gridfs/grid_file.py#L173

please let me know how can i solve the error using txmongo not my fixed.

**Comment by IlyaSkriblovsky** [comment]
Seems like you have no {files_id:1} key on chunks collection.

• Please provide the output of db.youcollection.chunks.getIndexes()
• Could you please provide code for minimal failing example?

**Comment by sagnol** [comment]
```python
@defer.inlineCallbacks
def extract_attachments(self, msg):
    #....
    for part in msg.walk():
        doc = { filename: part.get_filename() }
        yield self.gridfs.write(part.get_payload(decode=True))
```
```python
class MongoMailbox(pop3.Mailbox):
    # message task class implemented interfaces.IConsumer
    AppendFactory = _MongoMailboxAppendMessageTask
```

This is my code, and result is that  **_chunks_** collection and documents is created, but **_files_** collection and documents is not created.

**Comment by sagnol** [comment]
Sorry for late.
My project has already ended and deprecated.

Sorry for wate your time.
