### ISSUE TITLE
latest txmongo does not work with pymongo 3.7

### ISSUE THREAD

**Issue by billgates** [twisted/txmongo#246]
In pymongo 3.7 we have a method

    ./pymongo/bulk.py:94:def _merge_command(run, full_result, offset, result):

But txmongo uses it erroneously with 3 parameters

    ./txmongo/collection.py:69:def _merge_command(run, full_result, results):
    ./txmongo/collection.py:1371:            _merge_command(run, full_result, result)

That gives errors when using txmongo with pymongo 3.7 and higher
txmongo works with pymongo 3.6

**Comment by billgates** [comment]
closed - the following combination does work
- txmongo 18.2.0
- pymongo 3.7.2

**Comment by IlyaSkriblovsky** [comment]
Which lib did you updated to make it work: txmongo or pymongo?

**Comment by psi29a** [comment]
I believe he used an older version of txmongo with pymongo 3.7 then realized he had to bump txmongo as well which solved the issue.
