### ISSUE TITLE
does txmongo support transaction?

### ISSUE THREAD

**Issue by ygl-rg** [twisted/txmongo#273]
hi all

  I am curious whether txmongo supports transaction which is introduced since mongodb 4.0.

**Comment by IlyaSkriblovsky** [comment]
Unfortunately, no. I've started working on it while ago, but haven't time to complete. Still hoping to get it done eventually...

**Comment by ygl-rg** [comment]
thanks for your info.

Now I am using txmongo & pymongo together (pymongo is for multi docs transaction only)
