### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [twisted/txmongo#275]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine txmongo/_gridfs/grid_file.py and observe `propogate`, however expect to see `propagate`.
- Examine txmongo/_gridfs/__init__.py and observe `underlaying`, however expect to see `underlying`.
- Examine examples/deferreds/insert.py and observe `succes`, however expect to see `success`.
- Examine docs/source/status.rst and observe `maintance`, however expect to see `maintenance`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/txmongo/pull/new/bugfix_typos

Thanks.

**Comment by IlyaSkriblovsky** [comment]
Thank you, created pull request and merged
