### ISSUE TITLE
Args order

### ISSUE THREAD

**Issue by claytondaley** [twisted/txmongo#55]
Any particular reason that TxMongo's args order differ from PyMongo (e.g. `find()`)?  I'm migrating some code (and have other code that I'd prefer to have working on both platforms).  Obviously, I'll update the overlapping code to use kwargs, but it was an unexpected discovery (and might catch others).

**Comment by psi29a** [comment]
Since we are making changes here, I think it might be time to revisit this and get things back on track to being comparable to PyMongo.

**Comment by psi29a** [comment]
Any comments on this? @fiorix

**Comment by fiorix** [comment]
Well, so long as it's agreed that this change will break backwards compatibility with all existing code.

**Comment by psi29a** [comment]
I would hope to document this, with BIG warnings.

The other option would be to use *args **kwargs, so that argument order wouldn't matter. It would involve a bit more code though.

**Comment by fiorix** [comment]
Non-breaking changes are definitely better. Pretty sure the day you release a new version with a backwards incompatible call for such a popular function it'll break many people's env.

**Comment by claytondaley** [comment]
I certainly agree with @fiorix that BC breaks are bad.  It just strikes me as really weird not to mimic PyMongo's syntax and -- if the change is ever going to be made -- the sooner the better.  

All the more so if we expect a substantial upgrade that could attract a lot of migration from PyMongo.  Leaving the current syntax both (1) creates a migration hassle for migrating PyMongo users and, once migrated, (2) increases inertia for the current syntax.

**Comment by psi29a** [comment]
@claytondaley I agree with you, i rather have BC breaks that get txmongo on the right path than to let inertia hold us back.

From my point of view, we should have one big 15.0 release with all our bug fixes and new features. That way people can use that release without breakage.

The follow release, 15.1 will be the 'breakage'. This gives people the chance to pin against 15.0 until they fix their applications.

I really want to avoid having to do (if it works) *args **kargs tricks and have to carry that forward.

**Comment by claytondaley** [comment]
I like the basic plan, but wouldn't sync the TxMongo versions with Twisted.  Release the updates (pre BC) as 0.7 (the only release right now is 0.6) and make the BC change 1.0.

Separately, I don't think `args kwars` will help.  The two args without keywords will be `args[0]` and `args[1]`.  `filter` and `projection` are both dicts so a quick type check won't help.  You'd be stuck doing something complex to distinguish between the two possibly orders.

**Comment by psi29a** [comment]
The next release will be 15.0, we're already moved over to Twisted.

I'm afraid that you're correct.

**Comment by claytondaley** [comment]
I looked at a half dozen other repos on the Twisted organization and none were using the Twisted versioning. It certainly makes sense to match Twisted's versions if:

 - This version of TxMongo depends on Twisted 15.x (or)
 - TxMongo will be merged into the actual Twisted core

Otherwise, I think it makes more sense to chase PyMongo versioning.  Pick the approximately equivalent version of PyMongo whose features are substantially replicated.  Then someone who migrates from PyMongo has a sense of what features are available and what might be lost.

**Comment by psi29a** [comment]
Look again, for example:
https://github.com/twisted/ldaptor

The versioning scheme is purely date based. It was recommended by Glyph, Hawkowl and Hynek.

Now what you propose makes sense, but sadly we're a mix of features and deprecations that doesn't match up to any one version of PyMongo. :/

**Comment by IlyaSkriblovsky** [comment]
Fixed by #196
