### ISSUE TITLE
Get a new release (15.0) out the door!

### ISSUE THREAD

**Issue by psi29a** [twisted/txmongo#79]
This will be the release thread for the 15.0 milestone.

If there are comments about the current release, please ask/post them here. :)

@fiorix We good to go?
@IlyaSkriblovsky Any additional things we should do before release, you've done a lot already for this project.

**Comment by IlyaSkriblovsky** [comment]
I had no plans to commit anything right now since I'm pretty satisfied with current txmongo in my projects :)

Would be happy to see txmongo within Twisted!

**Comment by psi29a** [comment]
It already is, just time for a proper release. :P

**Comment by IlyaSkriblovsky** [comment]
What do you mean? I don't see txmongo in Twisted codebase in SVN.

**Comment by psi29a** [comment]
That's not what I meant, sorry for the confusion. I mean this:
https://github.com/twisted/txmongo

TxMongo is now like Ldaptor, in that it is now under Twisted's github organization. This should help taper forks down and encourage contribution to one central location.

**Comment by IlyaSkriblovsky** [comment]
Oh, I didn't noticed that I already writing this under twisted/txmongo url!

**Comment by fiorix** [comment]
:)

Good to go.

**Comment by trenton42** [comment]
We have been using this in production for a while now, and we don't have any outstanding issues.

**Comment by psi29a** [comment]
Released!
